add_test( [==[bitOrEncrypt and bitOrDecrypt]==] /home/vind/auto_edit_project/test/auto_edit_tests [==[bitOrEncrypt and bitOrDecrypt]==]  )
set_tests_properties( [==[bitOrEncrypt and bitOrDecrypt]==] PROPERTIES WORKING_DIRECTORY /home/vind/auto_edit_project/test)
add_test( [==[bitOrEncrypt and bitOrDecrypt with empty value]==] /home/vind/auto_edit_project/test/auto_edit_tests [==[bitOrEncrypt and bitOrDecrypt with empty value]==]  )
set_tests_properties( [==[bitOrEncrypt and bitOrDecrypt with empty value]==] PROPERTIES WORKING_DIRECTORY /home/vind/auto_edit_project/test)
add_test( [==[bitOrEncrypt and bitOrDecrypt with empty encryption key]==] /home/vind/auto_edit_project/test/auto_edit_tests [==[bitOrEncrypt and bitOrDecrypt with empty encryption key]==]  )
set_tests_properties( [==[bitOrEncrypt and bitOrDecrypt with empty encryption key]==] PROPERTIES WORKING_DIRECTORY /home/vind/auto_edit_project/test)
add_test( [==[VideoEditor trims and appends videos correctly]==] /home/vind/auto_edit_project/test/auto_edit_tests [==[VideoEditor trims and appends videos correctly]==]  )
set_tests_properties( [==[VideoEditor trims and appends videos correctly]==] PROPERTIES WORKING_DIRECTORY /home/vind/auto_edit_project/test)
add_test( [==[VideoEditor throws an error when trying to trim a video with invalid start or end second]==] /home/vind/auto_edit_project/test/auto_edit_tests [==[VideoEditor throws an error when trying to trim a video with invalid start or end second]==]  )
set_tests_properties( [==[VideoEditor throws an error when trying to trim a video with invalid start or end second]==] PROPERTIES WORKING_DIRECTORY /home/vind/auto_edit_project/test)
add_test( [==[VideoEditor throws an error when trying to append a video that does not exist]==] /home/vind/auto_edit_project/test/auto_edit_tests [==[VideoEditor throws an error when trying to append a video that does not exist]==]  )
set_tests_properties( [==[VideoEditor throws an error when trying to append a video that does not exist]==] PROPERTIES WORKING_DIRECTORY /home/vind/auto_edit_project/test)
set( auto_edit_tests_TESTS [==[bitOrEncrypt and bitOrDecrypt]==] [==[bitOrEncrypt and bitOrDecrypt with empty value]==] [==[bitOrEncrypt and bitOrDecrypt with empty encryption key]==] [==[VideoEditor trims and appends videos correctly]==] [==[VideoEditor throws an error when trying to trim a video with invalid start or end second]==] [==[VideoEditor throws an error when trying to append a video that does not exist]==])
