# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vind/auto_edit_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vind/auto_edit_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vind/auto_edit_project/CMakeFiles /home/vind/auto_edit_project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vind/auto_edit_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named auto_edit

# Build rule for target.
auto_edit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 auto_edit
.PHONY : auto_edit

# fast build rule for target.
auto_edit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/build
.PHONY : auto_edit/fast

#=============================================================================
# Target rules for targets named auto_edit_tests

# Build rule for target.
auto_edit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 auto_edit_tests
.PHONY : auto_edit_tests

# fast build rule for target.
auto_edit_tests/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/auto_edit_tests.dir/build.make test/CMakeFiles/auto_edit_tests.dir/build
.PHONY : auto_edit_tests/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/Experimental.dir/build.make test/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/Nightly.dir/build.make test/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/Continuous.dir/build.make test/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/NightlyMemoryCheck.dir/build.make test/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/NightlyStart.dir/build.make test/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/NightlyUpdate.dir/build.make test/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/NightlyConfigure.dir/build.make test/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/NightlyBuild.dir/build.make test/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/NightlyTest.dir/build.make test/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/NightlyCoverage.dir/build.make test/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/NightlyMemCheck.dir/build.make test/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/NightlySubmit.dir/build.make test/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ExperimentalStart.dir/build.make test/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ExperimentalUpdate.dir/build.make test/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ExperimentalConfigure.dir/build.make test/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ExperimentalBuild.dir/build.make test/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ExperimentalTest.dir/build.make test/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ExperimentalCoverage.dir/build.make test/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ExperimentalMemCheck.dir/build.make test/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ExperimentalSubmit.dir/build.make test/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ContinuousStart.dir/build.make test/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ContinuousUpdate.dir/build.make test/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ContinuousConfigure.dir/build.make test/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ContinuousBuild.dir/build.make test/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ContinuousTest.dir/build.make test/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ContinuousCoverage.dir/build.make test/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ContinuousMemCheck.dir/build.make test/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/ContinuousSubmit.dir/build.make test/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/main.cpp.s
.PHONY : main.cpp.s

src/api/api.o: src/api/api.cpp.o
.PHONY : src/api/api.o

# target to build an object file
src/api/api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/api/api.cpp.o
.PHONY : src/api/api.cpp.o

src/api/api.i: src/api/api.cpp.i
.PHONY : src/api/api.i

# target to preprocess a source file
src/api/api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/api/api.cpp.i
.PHONY : src/api/api.cpp.i

src/api/api.s: src/api/api.cpp.s
.PHONY : src/api/api.s

# target to generate assembly for a file
src/api/api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/api/api.cpp.s
.PHONY : src/api/api.cpp.s

src/api/twitch_api.o: src/api/twitch_api.cpp.o
.PHONY : src/api/twitch_api.o

# target to build an object file
src/api/twitch_api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/api/twitch_api.cpp.o
.PHONY : src/api/twitch_api.cpp.o

src/api/twitch_api.i: src/api/twitch_api.cpp.i
.PHONY : src/api/twitch_api.i

# target to preprocess a source file
src/api/twitch_api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/api/twitch_api.cpp.i
.PHONY : src/api/twitch_api.cpp.i

src/api/twitch_api.s: src/api/twitch_api.cpp.s
.PHONY : src/api/twitch_api.s

# target to generate assembly for a file
src/api/twitch_api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/api/twitch_api.cpp.s
.PHONY : src/api/twitch_api.cpp.s

src/api/youtube_api.o: src/api/youtube_api.cpp.o
.PHONY : src/api/youtube_api.o

# target to build an object file
src/api/youtube_api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/api/youtube_api.cpp.o
.PHONY : src/api/youtube_api.cpp.o

src/api/youtube_api.i: src/api/youtube_api.cpp.i
.PHONY : src/api/youtube_api.i

# target to preprocess a source file
src/api/youtube_api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/api/youtube_api.cpp.i
.PHONY : src/api/youtube_api.cpp.i

src/api/youtube_api.s: src/api/youtube_api.cpp.s
.PHONY : src/api/youtube_api.s

# target to generate assembly for a file
src/api/youtube_api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/api/youtube_api.cpp.s
.PHONY : src/api/youtube_api.cpp.s

src/app.o: src/app.cpp.o
.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/credential_encryption.o: src/credential_encryption.cpp.o
.PHONY : src/credential_encryption.o

# target to build an object file
src/credential_encryption.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/credential_encryption.cpp.o
.PHONY : src/credential_encryption.cpp.o

src/credential_encryption.i: src/credential_encryption.cpp.i
.PHONY : src/credential_encryption.i

# target to preprocess a source file
src/credential_encryption.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/credential_encryption.cpp.i
.PHONY : src/credential_encryption.cpp.i

src/credential_encryption.s: src/credential_encryption.cpp.s
.PHONY : src/credential_encryption.s

# target to generate assembly for a file
src/credential_encryption.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/credential_encryption.cpp.s
.PHONY : src/credential_encryption.cpp.s

src/io_util.o: src/io_util.cpp.o
.PHONY : src/io_util.o

# target to build an object file
src/io_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/io_util.cpp.o
.PHONY : src/io_util.cpp.o

src/io_util.i: src/io_util.cpp.i
.PHONY : src/io_util.i

# target to preprocess a source file
src/io_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/io_util.cpp.i
.PHONY : src/io_util.cpp.i

src/io_util.s: src/io_util.cpp.s
.PHONY : src/io_util.s

# target to generate assembly for a file
src/io_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/io_util.cpp.s
.PHONY : src/io_util.cpp.s

src/settings.o: src/settings.cpp.o
.PHONY : src/settings.o

# target to build an object file
src/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/settings.cpp.o
.PHONY : src/settings.cpp.o

src/settings.i: src/settings.cpp.i
.PHONY : src/settings.i

# target to preprocess a source file
src/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/settings.cpp.i
.PHONY : src/settings.cpp.i

src/settings.s: src/settings.cpp.s
.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/settings.cpp.s
.PHONY : src/settings.cpp.s

src/video_editor.o: src/video_editor.cpp.o
.PHONY : src/video_editor.o

# target to build an object file
src/video_editor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/video_editor.cpp.o
.PHONY : src/video_editor.cpp.o

src/video_editor.i: src/video_editor.cpp.i
.PHONY : src/video_editor.i

# target to preprocess a source file
src/video_editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/video_editor.cpp.i
.PHONY : src/video_editor.cpp.i

src/video_editor.s: src/video_editor.cpp.s
.PHONY : src/video_editor.s

# target to generate assembly for a file
src/video_editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/auto_edit.dir/build.make CMakeFiles/auto_edit.dir/src/video_editor.cpp.s
.PHONY : src/video_editor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... auto_edit"
	@echo "... auto_edit_tests"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/api/api.o"
	@echo "... src/api/api.i"
	@echo "... src/api/api.s"
	@echo "... src/api/twitch_api.o"
	@echo "... src/api/twitch_api.i"
	@echo "... src/api/twitch_api.s"
	@echo "... src/api/youtube_api.o"
	@echo "... src/api/youtube_api.i"
	@echo "... src/api/youtube_api.s"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/credential_encryption.o"
	@echo "... src/credential_encryption.i"
	@echo "... src/credential_encryption.s"
	@echo "... src/io_util.o"
	@echo "... src/io_util.i"
	@echo "... src/io_util.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
	@echo "... src/video_editor.o"
	@echo "... src/video_editor.i"
	@echo "... src/video_editor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

