# FindFFmpeg.cmake

find_path(FFMPEG_INCLUDE_DIR NAMES libavformat/avformat.h)
find_library(FFMPEG_LIBAVFORMAT NAMES avformat)
find_library(FFMPEG_LIBAVCODEC NAMES avcodec)
find_library(FFMPEG_LIBAVUTIL NAMES avutil)
find_library(FFMPEG_LIBSWSCALE NAMES swscale)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(FFmpeg DEFAULT_MSG FFMPEG_INCLUDE_DIR FFMPEG_LIBAVFORMAT FFMPEG_LIBAVCODEC FFMPEG_LIBAVUTIL FFMPEG_LIBSWSCALE)

if(FFMPEG_FOUND)
    set(FFMPEG_LIBRARIES ${FFMPEG_LIBAVFORMAT} ${FFMPEG_LIBAVCODEC} ${FFMPEG_LIBAVUTIL} ${FFMPEG_LIBSWSCALE})
endif()

mark_as_advanced(FFMPEG_INCLUDE_DIR FFMPEG_LIBAVFORMAT FFMPEG_LIBAVCODEC FFMPEG_LIBAVUTIL FFMPEG_LIBSWSCALE)