name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v6
      with:
        vcpkgArguments: 'cpr nlohmann-json curl'
        vcpkgDirectory: '${{ runner.workspace }}/doc/vcpkg/'  # Adjusted this line
        vcpkgGitCommitId: '47364fb'  
    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
    - name: Create Build Directory
      run: mkdir build
    - name: CMake
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/doc/vcpkg/scripts/buildsystems/vcpkg.cmake  # Adjusted this line
    - name: Build
      run: cmake --build build
    - name: Test
      run: ctest --test-dir build