name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Directory
      run: mkdir build
    - name: CMake
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build
    - name: Test
      run: ctest --test-dir build